version: '3.3'

services:

  shinyproxy:
    image: presstofan/shinyproxy-example
    # The labels section is where you specify configuration values for Traefik. 
    # Docker labels don’t do anything by themselves, but Traefik reads these so 
    # it knows how to treat containers.
    ports:
      - "8080"
    networks:
      - traefik-public
      - sp-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role==manager"
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.sp_shinyproxy.rule=Host(`app.databentobox.com`)"
          - "traefik.http.routers.sp_shinyproxy.entrypoints=http"
          - "traefik.http.middlewares.sp_shinyproxy.redirectscheme.scheme=https"
          - "traefik.http.middlewares.sp_shinyproxy.redirectscheme.permanent=true"
          - "traefik.http.routers.sp_shinyproxy-secured.rule=Host(`app.databentobox.com`)"
          - "traefik.http.routers.sp_shinyproxy-secured.entrypoints=https"
          - "traefik.http.routers.sp_shinyproxy-secured.tls.certresolver=le"
          - "traefik.http.services.sp_shinyproxy.loadbalancer.server.port=8080"
    volumes:
      - ./application/application.yml:/opt/shinyproxy/application.yml
      - /var/run/docker.sock:/var/run/docker.sock
  
  euler:
    image: presstofan/shiny-euler-app
    networks:
      - sp-net

networks:
  traefik-public:
    external: true
  sp-net:
    external: true